In [1]:
import numpy as np

In [2]:
grid_shape = (4,4)

In [4]:
def is_feasible(i,j,move="left"):
    if move == "left":
        if i-1 >= 0:
            return True
        else:
            return False
    elif move == "right":
        if i+1 <= 3:
            return True
        else:
            return False
    elif move == "up":
        if j+1 <= 3:
            return True
        else:
            return False
    elif move == "down":
        if j-1 >= 0:
            return True
        else:
            return False
    else:
        print("error")

In [5]:
def get_next_state(i,j,move="left"):
    if is_feasible(i,j,move):
        if move =="left":
            return i-1,j
        if move == "right":
            return i+1,j
        if move == "up":
            return i, j+1
        if move == "down":
            return i,j-1
    else:
        return i,j

In [20]:
def get_rew(i,j,move):
    i,j = get_next_state(i,j,move)
    if (i,j) == (3,3):
        return 1
    else:
        return -1

In [34]:
def get_policy_greedy(vals,i,j):
    if (i,j) == (3,3):
        print(i,j)
        return "terminal state"
    default = {"left":.25,
               "right":.25,
               "up" : .25,
               "down" : .25
              }
    v_left = vals[get_next_state(i,j,"left")]
    v_right = vals[get_next_state(i,j,"right")]
    v_up = vals[get_next_state(i,j,"up")]
    v_down = vals[get_next_state(i,j,"down")]
    max_val = max(v_left,v_right,v_up,v_down)
    
    #normalize and update default dict
    a = [v_left , v_right , v_up , v_down]
    c = a.count(max_val)
    if v_left==max_val:
        default["left"] = 1/c
    else:
        default["left"] = 0
    if v_right == max_val:
        default["right"] = 1/c
    else:
        default["right"] = 0
    if v_up==max_val:
        default["up"] = 1/c
    else:
        default["up"] = 0
    if v_down==max_val:
        default["down"] = 1/c
    else:
        default["down"] = 0
    
    return default

In [40]:
vals = np.zeros(grid_shape)
for e in range(20):
    print(vals)
    new_val = np.zeros(grid_shape)
    if e == 0:
        for i in range(grid_shape[0]):
            for j in range(grid_shape[1]):
                new_val[i,j] = .25*(vals[get_next_state(i,j,"left")] + get_rew(i,j,"left")) +\
                .25*(vals[get_next_state(i,j,"right")]+ get_rew(i,j,"right")) +\
                .25*(vals[get_next_state(i,j,"up")] + get_rew(i,j,"up")) +\
                .25*(vals[get_next_state(i,j,"down")] + get_rew(i,j,"down"))
    else:
        
        for i in range(grid_shape[0]):
            for j in range(grid_shape[1]):
                if (i==3 and j ==3):
                    pass
                else:
                    policy = get_policy_greedy(vals,i,j)
                    new_val[i,j] = policy["left"]*(vals[get_next_state(i,j,"left")] + get_rew(i,j,"left")) +\
                                   policy["right"]*(vals[get_next_state(i,j,"right")]+ get_rew(i,j,"right")) +\
                                   policy["up"]*(vals[get_next_state(i,j,"up")] + get_rew(i,j,"up")) +\
                                   policy["down"]*(vals[get_next_state(i,j,"down")] + get_rew(i,j,"down"))
    new_val[3,3] = 1
    vals = new_val

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[-1.  -1.  -1.  -1. ]
 [-1.  -1.  -1.  -1. ]
 [-1.  -1.  -1.  -0.5]
 [-1.  -1.  -0.5  1. ]]
[[-2.  -2.  -2.  -2. ]
 [-2.  -2.  -2.  -1.5]
 [-2.  -2.  -1.5  2. ]
 [-2.  -1.5  2.   1. ]]
[[-3.  -3.  -3.  -2.5]
 [-3.  -3.  -2.5  1. ]
 [-3.  -2.5  1.   1. ]
 [-2.5  1.   1.   1. ]]
[[-4.  -4.  -3.5  0. ]
 [-4.  -3.5  0.   0. ]
 [-3.5  0.   0.   0.5]
 [ 0.   0.   0.5  1. ]]
[[-5.  -4.5 -1.  -1. ]
 [-4.5 -1.  -1.  -0.5]
 [-1.  -1.  -0.5  2. ]
 [-1.  -0.5  2.   1. ]]
[[-5.5 -2.  -2.  -1.5]
 [-2.  -2.  -1.5  1. ]
 [-2.  -1.5  1.   1. ]
 [-1.5  1.   1.   1. ]]
[[-3.  -3.  -2.5  0. ]
 [-3.  -2.5  0.   0. ]
 [-2.5  0.   0.   0.5]
 [ 0.   0.   0.5  1. ]]
[[-4.  -3.5 -1.  -1. ]
 [-3.5 -1.  -1.  -0.5]
 [-1.  -1.  -0.5  2. ]
 [-1.  -0.5  2.   1. ]]
[[-4.5 -2.  -2.  -1.5]
 [-2.  -2.  -1.5  1. ]
 [-2.  -1.5  1.   1. ]
 [-1.5  1.   1.   1. ]]
[[-3.  -3.  -2.5  0. ]
 [-3.  -2.5  0.   0. ]
 [-2.5  0.   0.   0.5]
 [ 0.   0.   0.5  1. ]]
[[-4.  -3

In [24]:
u = {"h":1}

In [25]:
u["h"]

1

In [32]:
print((2,3) == (1,3))

False
