In [1]:
import tensorflow as tf
tf.enable_eager_execution()
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

1.12.0


In [2]:
model1 = keras.Sequential([
    keras.layers.Flatten(input_shape=(2, 2)),
    keras.layers.Dense(8, activation=tf.nn.relu),
    keras.layers.Dense(3, activation=tf.nn.softmax)
])

In [3]:
model1.compile(optimizer=tf.train.AdamOptimizer(), 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [4]:
model2 = keras.Sequential([model1,
    keras.layers.Dense(8, activation=tf.nn.relu),
    keras.layers.Dense(4, activation=tf.nn.softmax)
])

In [5]:
model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
sequential (Sequential)      (None, 3)                 67        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 32        
_________________________________________________________________
dense_3 (Dense)              (None, 4)                 36        
Total params: 135
Trainable params: 135
Non-trainable params: 0
_________________________________________________________________


In [6]:
model1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 4)                 0         
_________________________________________________________________
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 27        
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________


In [7]:
model1.compile(optimizer=tf.train.AdamOptimizer(), 
              loss='kullback_leibler_divergence')

In [8]:
model1.loss

'kullback_leibler_divergence'

In [9]:
model2.compile(optimizer=tf.train.AdamOptimizer(), 
              loss='mse')

In [10]:
inp_1 = np.asarray([[[1,2],[3,4]],
                   [[2,1],[5,6]]])
inp_1  = np.random.normal(size=(3,2,2))
inp_1.shape

(3, 2, 2)

In [11]:
model1.predict(inp_1)

array([[0.57373345, 0.23756997, 0.18869661],
       [0.39690855, 0.2641011 , 0.33899045],
       [0.02555401, 0.10367994, 0.87076604]], dtype=float32)

In [12]:
model2.predict(inp_1)

array([[0.23088543, 0.20351039, 0.22009033, 0.3455138 ],
       [0.18939637, 0.28636777, 0.21052882, 0.31370705],
       [0.10770659, 0.4160405 , 0.20954661, 0.2667063 ]], dtype=float32)

In [13]:
print(keras.evaluate(model2.get_output_at(0)))

AttributeError: module 'tensorflow._api.v1.keras' has no attribute 'evaluate'

In [14]:
model1.get_output_at(1)

<DeferredTensor 'None' shape=(?, 3) dtype=float32>

In [15]:
model1.layers[0].output

<DeferredTensor 'None' shape=(?, 4) dtype=float32>

In [16]:
layers = model1.layers

In [17]:
layers

In [18]:
layers[0](inp_1)

<tf.Tensor: id=210, shape=(3, 4), dtype=float64, numpy=
array([[-0.3242075 ,  0.57738673, -0.5903475 ,  1.22150841],
       [ 2.01168914,  0.32618242, -0.72076286,  1.13223517],
       [-0.15302752,  1.43059667, -0.19169716, -2.28608598]])>

In [19]:
model2.layers[0](inp_1)

InvalidArgumentError: cannot compute MatMul as input #0(zero-based) was expected to be a float tensor but is a double tensor [Op:MatMul]

In [20]:
model2.predict(inp_1)

array([[0.23088543, 0.20351039, 0.22009033, 0.3455138 ],
       [0.18939637, 0.28636777, 0.21052882, 0.31370705],
       [0.10770659, 0.4160405 , 0.20954661, 0.2667063 ]], dtype=float32)

In [21]:
model1.predict(inp_1)

array([[0.57373345, 0.23756997, 0.18869661],
       [0.39690855, 0.2641011 , 0.33899045],
       [0.02555401, 0.10367994, 0.87076604]], dtype=float32)

In [22]:
l = model2.layers[0]

In [30]:
l(inp_1.astype(np.float32))

<tf.Tensor: id=333, shape=(3, 3), dtype=float32, numpy=
array([[0.57373345, 0.23756997, 0.18869661],
       [0.39690855, 0.2641011 , 0.33899045],
       [0.02555401, 0.10367994, 0.87076604]], dtype=float32)>

In [33]:
op1 = np.asarray([[1.0],[0.0],[0.0]])

In [34]:
model1.fit(inp_1,op1)

Epoch 1/1
1/1 [==============================] - 0s 38ms/step - loss: 1.2202


In [35]:
model2.fit(inp_1,op1)

Epoch 1/1
1/1 [==============================] - 0s 58ms/step - loss: 0.2352


### all three outputs are same

In [36]:
model1.predict(inp_1)

array([[0.5679428 , 0.2402642 , 0.19179296],
       [0.39866188, 0.26376432, 0.3375738 ],
       [0.02580849, 0.10589895, 0.8682926 ]], dtype=float32)

In [37]:
### astype is required here
l(inp_1.astype(np.float32))

<tf.Tensor: id=1072, shape=(3, 3), dtype=float32, numpy=
array([[0.5679428 , 0.2402642 , 0.19179296],
       [0.39866188, 0.26376432, 0.3375738 ],
       [0.02580849, 0.10589895, 0.8682926 ]], dtype=float32)>

In [38]:
model2.layers[0](inp_1.astype(np.float32))

<tf.Tensor: id=1093, shape=(3, 3), dtype=float32, numpy=
array([[0.5679428 , 0.2402642 , 0.19179296],
       [0.39866188, 0.26376432, 0.3375738 ],
       [0.02580849, 0.10589895, 0.8682926 ]], dtype=float32)>